#+title: Intro Org Mode

[[./images/licorn.svg]]


* Hello World

This is an introduction to ~emacs~ and ~org-mode~.

Most of what I will write will come from tutorials, or things I learned myself. Let's have fun!

* Common Emacs Vocabulary
** Buffer
A buffer is a region of memory used to hold text that you are editing. Each file you open, as well as temporary texts like help messages, are displayed in buffers.
** Window
Refers to a portion of the Emacs frame where a buffer is displayed. You can split a frame into multiple windows.
** Frame
An Emacs frame is what most applications would call a window (the whole application window that can contain multiple Emacs windows).
** ~M~
Refers to Meta key such as ~Alt~ or ~Option~
** ~C~
Refers to ~Ctrl~ key (example `C-c` means Ctrl+C)
** ~SPC~
Refers to space bar (used in Doom Emacs)

* Common Key Bindings
** TODO Commands
- ~M x~ run and list available commands
** DONE Buffer
- ~SPC b i~ list open buffers
- ~SPC b n~ go to next buffer
- ~SPC b p~ go to previous buffer
- ~SPC b k~ kill current buffer
** TODO Navigation
- ~SPC .~ navigate through directories (open current one)
** TODO Evil Mode
- ~gg~ go to top file
- ~G~ go to bottom file

-----------

* Heading 1
** Heading 2
*** Heading 3
**** Heading 4
***** Heading 5
****** Heading 6
